name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_test:
    strategy:
      matrix:
        node-version: ['8', '10', '12']
        os: ['ubuntu-latest', 'windows-latest']

    runs-on: ${{ matrix.os }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout code
        uses: actions/checkout@v2

      - name: use node version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, test
        run: |
          npm install
          npm run build --if-present
          npm run test

      - name: Archive build output
        uses: actions/upload-artifact@v1
        with: 
          name: code-coverage-report-${{ matrix.os }}-node${{ matrix.node_version }}
          path: coverage/

      # - name: Archive code coverage report
      #   uses: actions/upload-artifact@v1
      #   with: 
      #     name: app
      #     path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    
    steps:
      # - name: Retrieve build output from previous job
      #   uses: actions/download-artifact@v1
      #   with:
      #     name: app
      #     path: .

      - name: "Login via Azure CLI"
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      # - name: "Run Azure Functions action"
      #   uses: Azure/functions-action@v1
      #   id: fa
      #   with: 
      #     app-name: phpwvlfunction

      - name: Deploy function
        run: echo "Deployment completed"

